### ISSUE TITLE
Initialising, verifying, and linking Django app with RDS

### ISSUE THREAD

**Issue by jappurohit041** [NCSU-SE-Fall-24/WolfLease#7]

**Comment by Kenil2211** [comment]
![issue-1 1](https://github.com/user-attachments/assets/94b0cbeb-a62f-483c-8d7b-5e203b2b351a)
![issue-1](https://github.com/user-attachments/assets/378864cd-ee65-4676-b6a5-c1837121cf7a)
Verified And working!!
